/* INFUCOCO 療癒宇宙 — 100 款療癒遊戲資料（含難度 lv） */
window.GAMES=[
{id:"g01",lv:2,t:"接住彩虹氣球",c:"react",ty:"catch",i:"🎈",d:"接住所有落下的療癒小物，別讓它們掉落。",p:2},
{id:"g02",lv:1,t:"星星收集器",c:"react",ty:"catch",i:"⭐",d:"接住所有落下的療癒小物，別讓它們掉落。",p:2},
{id:"g03",lv:3,t:"拯救飄落的種子",c:"react",ty:"catch",i:"🌱",d:"接住所有落下的療癒小物，別讓它們掉落。",p:2},
{id:"g04",lv:2,t:"捕捉發光的螢火蟲",c:"react",ty:"catch",i:"✨",d:"接住所有落下的療癒小物，別讓它們掉落。",p:2},
{id:"g05",lv:1,t:"接住流星糖",c:"react",ty:"catch",i:"🌠",d:"接住所有落下的療癒小物，別讓它們掉落。",p:2},
{id:"g06",lv:3,t:"泡泡手指畫",c:"react",ty:"whack",i:"🫧",d:"看到目標就點下去，考驗你的反應力。",p:2},
{id:"g07",lv:2,t:"點泡泡大賽",c:"react",ty:"reaction",i:"🫧",d:"快速反應，抓到就得分！",p:2},
{id:"g08",lv:1,t:"反應力挑戰",c:"react",ty:"reaction",i:"⚡",d:"快速反應，抓到就得分！",p:2},
{id:"g09",lv:3,t:"抓跳跳糖",c:"react",ty:"whack",i:"🍬",d:"看到目標就點下去，考驗你的反應力。",p:2},
{id:"g10",lv:2,t:"踩到星星就得分",c:"react",ty:"whack",i:"🌟",d:"看到目標就點下去，考驗你的反應力。",p:2},
{id:"g11",lv:1,t:"雲朵接物",c:"react",ty:"catch",i:"☁️",d:"接住所有落下的療癒小物，別讓它們掉落。",p:2},
{id:"g12",lv:3,t:"花瓣收集",c:"react",ty:"catch",i:"🌸",d:"接住所有落下的療癒小物，別讓它們掉落。",p:2},
{id:"g13",lv:2,t:"月亮鞦韆抓星",c:"react",ty:"catch",i:"🌙",d:"接住所有落下的療癒小物，別讓它們掉落。",p:2},
{id:"g14",lv:1,t:"拯救小燈籠",c:"react",ty:"catch",i:"🏮",d:"接住所有落下的療癒小物，別讓它們掉落。",p:2},
{id:"g15",lv:3,t:"彩虹泡泡接接樂",c:"react",ty:"reaction",i:"🌈",d:"快速反應，抓到就得分！",p:2},
{id:"g16",lv:2,t:"流星捕捉大師",c:"react",ty:"timing",i:"☄️",d:"在對的時機按下去，節奏感大考驗。",p:2},
{id:"g17",lv:1,t:"影子捕捉師",c:"react",ty:"reaction",i:"🌓",d:"快速反應，抓到就得分！",p:2},
{id:"g18",lv:3,t:"配對·彩虹蛋",c:"puzzle",ty:"memory",i:"🥚",d:"翻開兩張牌，找出相同的那一對。",p:2},
{id:"g19",lv:2,t:"迷宮·星星之路",c:"puzzle",ty:"order",i:"🛤️",d:"按正確順序排列，考驗邏輯。",p:2},
{id:"g20",lv:1,t:"拼圖·月光碎片",c:"puzzle",ty:"sequence",i:"🧩",d:"記住順序，跟著重現。",p:2},
{id:"g21",lv:3,t:"數一數·螢火蟲",c:"puzzle",ty:"count",i:"🐛",d:"數一數有幾個，填上正確答案。",p:2},
{id:"g22",lv:2,t:"順序·四季列車",c:"puzzle",ty:"order",i:"🚂",d:"按正確順序排列，考驗邏輯。",p:2},
{id:"g23",lv:1,t:"記憶·花園卡片",c:"puzzle",ty:"memory",i:"🃏",d:"翻開兩張牌，找出相同的那一對。",p:2},
{id:"g24",lv:3,t:"顏色·彩虹心情",c:"puzzle",ty:"match",i:"🌈",d:"把相同主題連在一起。",p:2},
{id:"g25",lv:2,t:"天平·閃亮星星",c:"puzzle",ty:"count",i:"⚖️",d:"數一數有幾個，填上正確答案。",p:2},
{id:"g26",lv:1,t:"找一找·藏起來的月亮",c:"puzzle",ty:"order",i:"🌙",d:"按正確順序排列，考驗邏輯。",p:2},
{id:"g27",lv:3,t:"連連看·小宇宙",c:"puzzle",ty:"match",i:"🔗",d:"把相同主題連在一起。",p:2},
{id:"g28",lv:2,t:"推理·星星密碼",c:"puzzle",ty:"quiz",i:"🔑",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g29",lv:1,t:"時機·跳過雲洞",c:"puzzle",ty:"timing",i:"🕳️",d:"在對的時機按下去，節奏感大考驗。",p:2},
{id:"g30",lv:3,t:"排列·星空拼圖",c:"puzzle",ty:"sequence",i:"🧩",d:"記住順序，跟著重現。",p:2},
{id:"g31",lv:2,t:"邏輯·螢火蟲排隊",c:"puzzle",ty:"order",i:"🐝",d:"按正確順序排列，考驗邏輯。",p:2},
{id:"g32",lv:1,t:"算一算·星星糖果",c:"puzzle",ty:"count",i:"🍬",d:"數一數有幾個，填上正確答案。",p:2},
{id:"g33",lv:3,t:"記憶·動物夥伴",c:"puzzle",ty:"memory",i:"🐾",d:"翻開兩張牌，找出相同的那一對。",p:2},
{id:"g34",lv:2,t:"順序·銀河列車",c:"puzzle",ty:"order",i:"🚆",d:"按正確順序排列，考驗邏輯。",p:2},
{id:"g35",lv:1,t:"寓言問答·種子",c:"fable",ty:"quiz",i:"🌱",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g36",lv:3,t:"寓言問答·螢火蟲",c:"fable",ty:"quiz",i:"✨",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g37",lv:2,t:"寓言問答·月亮",c:"fable",ty:"quiz",i:"🌙",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g38",lv:1,t:"寓言問答·彩虹",c:"fable",ty:"quiz",i:"🌈",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g39",lv:3,t:"寓言問答·煙火",c:"fable",ty:"quiz",i:"🎆",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g40",lv:2,t:"寓言問答·書",c:"fable",ty:"quiz",i:"📖",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g41",lv:1,t:"寓言問答·咖啡",c:"fable",ty:"quiz",i:"☕",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g42",lv:3,t:"寓言問答·橋",c:"fable",ty:"quiz",i:"🌉",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g43",lv:2,t:"寓言問答·雲朵",c:"fable",ty:"quiz",i:"☁️",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g44",lv:1,t:"寓言問答·花園",c:"fable",ty:"quiz",i:"🌸",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g45",lv:3,t:"寓言問答·海洋",c:"fable",ty:"quiz",i:"🌊",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g46",lv:2,t:"寓言問答·星星",c:"fable",ty:"quiz",i:"⭐",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g47",lv:1,t:"寓言問答·風箏",c:"fable",ty:"quiz",i:"🪁",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g48",lv:3,t:"寓言問答·燈籠",c:"fable",ty:"quiz",i:"🏮",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g49",lv:2,t:"寓言問答·雪人",c:"fable",ty:"quiz",i:"⛄",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g50",lv:1,t:"寓言問答·向日葵",c:"fable",ty:"quiz",i:"🌻",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g51",lv:3,t:"寓言問答·露珠",c:"fable",ty:"quiz",i:"💧",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g52",lv:2,t:"餵貓咪吃魚",c:"pet",ty:"quiz",i:"🐟",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g53",lv:1,t:"幫小狗洗澡",c:"pet",ty:"quiz",i:"🛁",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g54",lv:3,t:"給花澆水",c:"pet",ty:"quiz",i:"💧",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g55",lv:2,t:"療癒抱抱計時",c:"pet",ty:"quiz",i:"🤗",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g56",lv:1,t:"貓咪散步節奏",c:"pet",ty:"quiz",i:"🐈",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g57",lv:3,t:"數貓咪抓尾巴",c:"pet",ty:"quiz",i:"🐱",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g58",lv:2,t:"水豚泡澡",c:"pet",ty:"quiz",i:"🦫",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g59",lv:1,t:"小鳥飛舞抓食",c:"pet",ty:"quiz",i:"🐦",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g60",lv:3,t:"摸兔兔耳朵",c:"pet",ty:"quiz",i:"🐰",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g61",lv:2,t:"寵物美容順序",c:"pet",ty:"order",i:"✂️",d:"按正確順序排列，考驗邏輯。",p:2},
{id:"g62",lv:1,t:"狗狗接飛盤",c:"pet",ty:"quiz",i:"🥏",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g63",lv:3,t:"小貓追毛線球",c:"pet",ty:"quiz",i:"🧶",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g64",lv:2,t:"療癒咕嚕聲記憶",c:"pet",ty:"memory",i:"😽",d:"翻開兩張牌，找出相同的那一對。",p:2},
{id:"g65",lv:1,t:"餵金魚",c:"pet",ty:"quiz",i:"🐠",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g66",lv:3,t:"幫小鳥梳羽毛",c:"pet",ty:"quiz",i:"🪶",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g67",lv:2,t:"小刺蝟滾球",c:"pet",ty:"quiz",i:"🦔",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g68",lv:1,t:"點泡泡大賽",c:"arcade",ty:"quiz",i:"🫧",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g69",lv:3,t:"打地鼠·小怪獸",c:"arcade",ty:"quiz",i:"🦔",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g70",lv:2,t:"按節奏·拍拍手",c:"arcade",ty:"quiz",i:"👏",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g71",lv:1,t:"猜拳·贏過infucoco",c:"arcade",ty:"quiz",i:"✌️",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g72",lv:3,t:"彈跳·氣球保衛",c:"arcade",ty:"quiz",i:"🎈",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g73",lv:2,t:"轉盤·幸運星",c:"arcade",ty:"quiz",i:"🎡",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g74",lv:1,t:"抓娃娃·星星",c:"arcade",ty:"quiz",i:"🧸",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g75",lv:3,t:"賽跑·跨欄",c:"arcade",ty:"quiz",i:"🏃",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g76",lv:2,t:"釣魚·星之河",c:"arcade",ty:"quiz",i:"🎣",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g77",lv:1,t:"滾球·彈珠台",c:"arcade",ty:"quiz",i:"🪙",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g78",lv:3,t:"射擊·泡泡槍",c:"arcade",ty:"quiz",i:"🔫",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g79",lv:2,t:"平衡·疊疊樂",c:"arcade",ty:"quiz",i:"🧱",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g80",lv:1,t:"套圈·圈星星",c:"arcade",ty:"quiz",i:"⭕",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g81",lv:3,t:"反應·躲隕石",c:"arcade",ty:"quiz",i:"☄️",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g82",lv:2,t:"節奏·鼓點",c:"arcade",ty:"quiz",i:"🥁",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g83",lv:1,t:"彈跳·跳跳糖",c:"arcade",ty:"quiz",i:"🍬",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g84",lv:3,t:"故事接龍·給infucoco",c:"creative",ty:"quiz",i:"📖",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g85",lv:2,t:"畫一道彩虹",c:"creative",ty:"quiz",i:"🌈",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g86",lv:1,t:"幫角色挑衣服",c:"creative",ty:"quiz",i:"👗",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g87",lv:3,t:"寫一句療癒語",c:"creative",ty:"quiz",i:"💬",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g88",lv:2,t:"配色·心情調色盤",c:"creative",ty:"quiz",i:"🎨",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g89",lv:1,t:"給小動物取名",c:"creative",ty:"quiz",i:"🐾",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g90",lv:3,t:"編一支小舞步",c:"creative",ty:"quiz",i:"💃",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g91",lv:2,t:"設計一張貼圖",c:"creative",ty:"quiz",i:"🖼️",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g92",lv:1,t:"選一首歌給今天",c:"creative",ty:"quiz",i:"🎵",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g93",lv:3,t:"幫花園種新花",c:"creative",ty:"quiz",i:"🌷",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g94",lv:2,t:"寫一封信給未來",c:"creative",ty:"quiz",i:"✉️",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g95",lv:1,t:"做一張療癒卡片",c:"creative",ty:"quiz",i:"💌",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g96",lv:3,t:"幫星星排隊形",c:"creative",ty:"quiz",i:"⭐",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g97",lv:2,t:"發明一個新動物",c:"creative",ty:"quiz",i:"🦄",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g98",lv:1,t:"幫infucoco找回家的路",c:"creative",ty:"quiz",i:"🏡",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g99",lv:3,t:"編一首搖籃曲",c:"creative",ty:"quiz",i:"🎶",d:"回答療癒小問題，看看你多了解 infucoco。",p:2},
{id:"g100",lv:2,t:"設計一個小島",c:"creative",ty:"quiz",i:"🏝️",d:"回答療癒小問題，看看你多了解 infucoco。",p:2}
];
window.GAME_MAP={};
GAMES.forEach(function(g){GAME_MAP[g.id]=g});